2025-04-24 09:08:50 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:09:11 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:09:13 | INFO | django.server | "GET / HTTP/1.1" 200 3285
2025-04-24 09:09:13 | INFO | django.server | "GET /media/tests/image6_vVIDswq.png HTTP/1.1" 304 0
2025-04-24 09:09:13 | INFO | django.server | "GET /media/tests/image5_SBf1jTL.png HTTP/1.1" 304 0
2025-04-24 09:09:15 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 09:09:40 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 09:09:40 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 09:09:45 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 1818
2025-04-24 09:10:19 | ERROR | django.request | Internal Server Error: /tests/students/report/2/
Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Django\testapp\testapp\tests\views.py", line 383, in generate_student_report
    document.add_paragraph(f"Дата создания: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
                                             ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
2025-04-24 09:10:19 | ERROR | django.server | "GET /tests/students/report/2/ HTTP/1.1" 500 70139
2025-04-24 09:13:43 | ERROR | django.request | Internal Server Error: /tests/students/report/2/
Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Django\testapp\testapp\tests\views.py", line 383, in generate_student_report
    document.add_paragraph(f"Дата создания: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
                                             ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
2025-04-24 09:13:43 | ERROR | django.server | "GET /tests/students/report/2/ HTTP/1.1" 500 70276
2025-04-24 09:13:46 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 1818
2025-04-24 09:13:47 | ERROR | django.request | Internal Server Error: /tests/students/report/2/
Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Django\testapp\testapp\tests\views.py", line 383, in generate_student_report
    document.add_paragraph(f"Дата создания: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
                                             ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
2025-04-24 09:13:47 | ERROR | django.server | "GET /tests/students/report/2/ HTTP/1.1" 500 70139
2025-04-24 09:14:53 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\tests\views.py changed, reloading.
2025-04-24 09:14:54 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:14:57 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\tests\views.py changed, reloading.
2025-04-24 09:14:58 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:16:23 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\tests\views.py changed, reloading.
2025-04-24 09:16:24 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:16:27 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\tests\views.py changed, reloading.
2025-04-24 09:16:28 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:16:39 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 1818
2025-04-24 09:16:41 | ERROR | django.request | Internal Server Error: /tests/students/report/2/
Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Django\testapp\testapp\tests\views.py", line 416, in generate_student_report
    response = HttpResponse(
               ^^^^^^^^^^^^
NameError: name 'HttpResponse' is not defined
2025-04-24 09:16:41 | ERROR | django.server | "GET /tests/students/report/2/ HTTP/1.1" 500 71739
2025-04-24 09:16:55 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\tests\views.py changed, reloading.
2025-04-24 09:16:56 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:16:59 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 1818
2025-04-24 09:17:00 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 1818
2025-04-24 09:17:01 | INFO | django.server | "GET /tests/students/report/2/ HTTP/1.1" 200 37076
2025-04-24 09:17:36 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 09:18:37 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\tests\views.py changed, reloading.
2025-04-24 09:18:38 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:18:39 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 1818
2025-04-24 09:18:40 | INFO | django.server | "GET /tests/students/report/2/ HTTP/1.1" 200 37010
2025-04-24 09:37:56 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:37:57 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 09:38:00 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 09:38:00 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 09:38:06 | INFO | django.server | "POST /users/login/ HTTP/1.1" 200 1430
2025-04-24 09:38:13 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 09:38:13 | INFO | django.server | "GET / HTTP/1.1" 200 3997
2025-04-24 09:38:14 | INFO | django.server | "GET /admin/ HTTP/1.1" 200 1129
2025-04-24 09:38:16 | INFO | django.server | "GET /users/logs/ HTTP/1.1" 200 1065
2025-04-24 09:38:59 | INFO | django.server | "GET /users/logs/ HTTP/1.1" 200 1785
2025-04-24 09:39:16 | INFO | django.server | "GET /users/logs/ HTTP/1.1" 200 1761
2025-04-24 09:54:23 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 09:54:25 | INFO | django.server | "GET /admin/ HTTP/1.1" 200 1129
2025-04-24 09:54:35 | INFO | django.server | "GET /admin/users/ HTTP/1.1" 200 3593
2025-04-24 09:54:37 | INFO | django.server | "GET /admin/users/create/ HTTP/1.1" 200 4157
2025-04-24 09:54:49 | INFO | django.server | "GET /admin/users/4/update/ HTTP/1.1" 200 4287
2025-04-24 09:55:24 | INFO | django.server | "GET /admin/groups/ HTTP/1.1" 200 2729
2025-04-24 09:55:48 | INFO | django.server | "GET /admin/roles/ HTTP/1.1" 200 2709
2025-04-24 10:35:51 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 10:35:51 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:36:02 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 10:36:02 | INFO | django.server | "GET / HTTP/1.1" 200 3552
2025-04-24 10:36:02 | INFO | django.server | "GET /media/tests/image5_SBf1jTL.png HTTP/1.1" 304 0
2025-04-24 10:36:02 | INFO | django.server | "GET /media/tests/image6_vVIDswq.png HTTP/1.1" 304 0
2025-04-24 10:36:32 | INFO | django.server | "GET /tests/show_test/2/ HTTP/1.1" 200 1386
2025-04-24 10:36:32 | INFO | django.server | "GET /media/tests/image8_nALvNqb.png HTTP/1.1" 200 58323
2025-04-24 10:36:36 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 10:36:36 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:36:42 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 10:36:42 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 10:36:46 | INFO | django.server | "GET /tests/add_question/2/ HTTP/1.1" 200 4186
2025-04-24 10:36:46 | INFO | django.server | "GET /static/tests/create.css HTTP/1.1" 304 0
2025-04-24 10:37:05 | INFO | django.server | "POST /tests/add_question/2/ HTTP/1.1" 302 0
2025-04-24 10:37:05 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 10:37:07 | INFO | django.server | "GET /tests/questions_list/2/ HTTP/1.1" 200 2471
2025-04-24 10:37:12 | INFO | django.server | "GET /tests/update_question/4/ HTTP/1.1" 200 7136
2025-04-24 10:37:18 | INFO | django.server | "POST /tests/update_question/4/ HTTP/1.1" 302 0
2025-04-24 10:37:18 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 10:37:20 | INFO | django.server | "GET /tests/questions_list/2/ HTTP/1.1" 200 2471
2025-04-24 10:38:01 | INFO | django.server | "GET /tests/personal_type/1/ HTTP/1.1" 200 1369
2025-04-24 10:38:04 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 1818
2025-04-24 10:39:53 | INFO | django.server | "GET /tests/add_result/2/ HTTP/1.1" 200 4137
2025-04-24 10:40:16 | INFO | django.server | "POST /tests/add_result/2/ HTTP/1.1" 302 0
2025-04-24 10:40:16 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 10:40:20 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 10:40:20 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:40:32 | INFO | django.server | "POST /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:40:40 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 10:40:40 | INFO | django.server | "GET / HTTP/1.1" 200 2796
2025-04-24 10:41:38 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 10:41:38 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:41:45 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 10:41:45 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 10:41:49 | INFO | django.server | "GET /tests/students_list HTTP/1.1" 200 6527
2025-04-24 10:42:05 | INFO | django.server | "GET /tests/assign_test/1/ HTTP/1.1" 200 2058
2025-04-24 10:42:11 | INFO | django.server | "POST /tests/assign_test/1/ HTTP/1.1" 302 0
2025-04-24 10:42:11 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 10:42:14 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 10:42:14 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:42:22 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 10:42:22 | INFO | django.server | "GET / HTTP/1.1" 200 3141
2025-04-24 10:42:26 | INFO | django.server | "GET /users/my_recommendations/ HTTP/1.1" 200 1371
2025-04-24 10:42:27 | INFO | django.server | "GET / HTTP/1.1" 200 3141
2025-04-24 10:42:31 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 10:42:31 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:51:36 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 10:51:36 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 10:52:30 | INFO | django.server | "GET /tests/create/ HTTP/1.1" 200 2634
2025-04-24 10:55:59 | INFO | django.server | "GET /tests/students_list HTTP/1.1" 200 6527
2025-04-24 10:56:06 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 10:56:54 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 10:56:54 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:57:04 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 10:57:04 | INFO | django.server | "GET / HTTP/1.1" 200 3552
2025-04-24 10:57:06 | INFO | django.server | "GET /tests/show_test/2/ HTTP/1.1" 200 1386
2025-04-24 10:57:11 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 10:57:11 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 10:57:18 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 10:57:18 | INFO | django.server | "GET / HTTP/1.1" 200 4202
2025-04-24 11:15:54 | INFO | django.server | "GET /tests/create/ HTTP/1.1" 200 2634
2025-04-24 11:16:25 | INFO | django.server | "POST /tests/create/ HTTP/1.1" 302 0
2025-04-24 11:16:25 | INFO | django.server | "GET / HTTP/1.1" 200 4779
2025-04-24 11:16:25 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 200 8210
2025-04-24 11:16:27 | INFO | django.server | "GET /tests/add_question/3/ HTTP/1.1" 200 4186
2025-04-24 11:16:45 | INFO | django.server | "POST /tests/add_question/3/ HTTP/1.1" 302 0
2025-04-24 11:16:45 | INFO | django.server | "GET / HTTP/1.1" 200 4779
2025-04-24 11:16:45 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 11:16:47 | INFO | django.server | "GET /tests/add_result/3/ HTTP/1.1" 200 4137
2025-04-24 11:17:09 | INFO | django.server | "POST /tests/add_result/3/ HTTP/1.1" 302 0
2025-04-24 11:17:09 | INFO | django.server | "GET / HTTP/1.1" 200 4779
2025-04-24 11:17:09 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 11:17:22 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 2053
2025-04-24 11:17:27 | INFO | django.server | "GET /tests/assign_test/3/ HTTP/1.1" 200 2269
2025-04-24 11:17:31 | INFO | django.server | "POST /tests/assign_test/3/ HTTP/1.1" 302 0
2025-04-24 11:17:31 | INFO | django.server | "GET / HTTP/1.1" 200 4779
2025-04-24 11:17:31 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 11:17:40 | INFO | django.server | "GET /tests/questions_list/3/ HTTP/1.1" 200 2447
2025-04-24 11:17:44 | INFO | django.server | "GET /tests/questions_list/2/ HTTP/1.1" 200 2471
2025-04-24 11:17:49 | INFO | django.server | "GET /tests/questions_list/1/ HTTP/1.1" 200 3352
2025-04-24 11:17:50 | INFO | django.server | "GET /tests/update_question/1/ HTTP/1.1" 200 7166
2025-04-24 11:18:10 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 11:18:10 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 11:18:19 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 11:18:19 | INFO | django.server | "GET / HTTP/1.1" 200 3829
2025-04-24 11:18:19 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 11:18:32 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 11:18:32 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 11:18:37 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 11:18:37 | INFO | django.server | "GET / HTTP/1.1" 200 4779
2025-04-24 11:18:37 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 11:18:38 | INFO | django.server | "GET /tests/students_list HTTP/1.1" 200 6527
2025-04-24 11:18:40 | INFO | django.server | "GET /tests/students_list?sort=last_name&direction=desc HTTP/1.1" 200 6586
2025-04-24 11:18:44 | INFO | django.server | "GET /tests/students_list?search=&group=&personality=2 HTTP/1.1" 200 4625
2025-04-24 11:18:47 | INFO | django.server | "GET /tests/students_list HTTP/1.1" 200 6527
2025-04-24 11:18:52 | INFO | django.server | "GET /tests/test_results_chart HTTP/1.1" 200 1859
2025-04-24 11:20:28 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 11:20:28 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 11:20:37 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 11:20:37 | INFO | django.server | "GET / HTTP/1.1" 200 3829
2025-04-24 11:20:37 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 11:20:40 | INFO | django.server | "GET /tests/test_result/1/ HTTP/1.1" 200 1454
2025-04-24 11:20:40 | INFO | django.server | "GET /media/tests/image_21_b6hWDlr.png HTTP/1.1" 200 49587
2025-04-24 11:20:44 | INFO | django.server | "GET /tests/show_test/3/ HTTP/1.1" 200 1307
2025-04-24 11:20:44 | INFO | django.server | "GET /media/tests/image_21_GPq9JSD.png HTTP/1.1" 200 49587
2025-04-24 11:20:45 | INFO | django.server | "GET /tests/questions_test/3/ HTTP/1.1" 200 2748
2025-04-24 11:20:46 | INFO | django.server | "POST /tests/questions_test/3/ HTTP/1.1" 302 0
2025-04-24 11:20:47 | INFO | django.server | "GET /tests/test_result/3/ HTTP/1.1" 200 1494
2025-04-24 11:20:49 | INFO | django.server | "GET / HTTP/1.1" 200 3950
2025-04-24 11:20:51 | INFO | django.server | "GET /users/my_recommendations/ HTTP/1.1" 200 1805
2025-04-24 11:21:39 | INFO | django.server | "GET / HTTP/1.1" 200 3950
2025-04-24 11:21:39 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 11:21:43 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 11:21:43 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 11:21:48 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 11:21:48 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 11:21:49 | INFO | django.server | "GET /admin/ HTTP/1.1" 200 1129
2025-04-24 11:21:53 | INFO | django.server | "GET /admin/roles/ HTTP/1.1" 200 2709
2025-04-24 11:22:18 | INFO | django.server | "GET /admin/groups/ HTTP/1.1" 200 2729
2025-04-24 11:22:30 | INFO | django.server | "GET /admin/roles/ HTTP/1.1" 200 2709
2025-04-24 11:22:35 | INFO | django.server | "GET /admin/roles/ HTTP/1.1" 200 2709
2025-04-24 11:22:40 | INFO | django.server | "GET /users/logs/ HTTP/1.1" 200 1784
2025-04-24 12:11:04 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 12:11:06 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 12:11:06 | INFO | django.server | "GET /media/tests/image6_vVIDswq.png HTTP/1.1" 304 0
2025-04-24 12:11:06 | INFO | django.server | "GET /media/tests/image5_SBf1jTL.png HTTP/1.1" 304 0
2025-04-24 12:11:06 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 12:11:06 | WARNING | django.request | Not Found: /favicon.ico
2025-04-24 12:11:06 | WARNING | django.server | "GET /favicon.ico HTTP/1.1" 404 2987
2025-04-24 12:11:13 | INFO | django.server | "GET /tests/add_result/1/ HTTP/1.1" 302 0
2025-04-24 12:11:13 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 12:11:16 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 12:11:16 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 12:11:26 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 12:11:26 | INFO | django.server | "GET / HTTP/1.1" 200 4779
2025-04-24 12:11:34 | INFO | django.server | "GET /tests/create/ HTTP/1.1" 200 2634
2025-04-24 12:11:43 | INFO | django.server | "GET /tests/add_result/3/ HTTP/1.1" 200 4137
2025-04-24 12:12:06 | INFO | django.server | "GET /tests/personal_type/2/ HTTP/1.1" 200 1997
2025-04-24 12:12:21 | INFO | django.server | "GET /tests/questions_list/1/ HTTP/1.1" 200 3352
2025-04-24 12:12:25 | INFO | django.server | "GET /tests/students_list HTTP/1.1" 200 6585
2025-04-24 12:12:34 | INFO | django.server | "GET /tests/test_results_chart HTTP/1.1" 200 1861
2025-04-24 12:13:48 | INFO | django.server | "GET / HTTP/1.1" 200 4779
2025-04-24 12:15:28 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 12:15:28 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 12:15:38 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 12:15:38 | INFO | django.server | "GET / HTTP/1.1" 200 4779
2025-04-24 12:15:42 | INFO | django.server | "GET /tests/add_question/2/ HTTP/1.1" 200 4186
2025-04-24 12:16:40 | INFO | django.server | "GET /tests/add_question/2/ HTTP/1.1" 200 4186
2025-04-24 12:16:55 | INFO | django.server | "GET /tests/questions_list/2/ HTTP/1.1" 200 2471
2025-04-24 12:16:57 | INFO | django.server | "GET /tests/update_question/4/ HTTP/1.1" 200 7136
2025-04-24 12:19:39 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 12:19:39 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 12:19:48 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 12:19:48 | INFO | django.server | "GET / HTTP/1.1" 200 3950
2025-04-24 12:19:48 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 12:19:51 | INFO | django.server | "GET /tests/show_test/2/ HTTP/1.1" 200 1386
2025-04-24 12:19:51 | INFO | django.server | "GET /media/tests/image8_nALvNqb.png HTTP/1.1" 304 0
2025-04-24 12:19:52 | INFO | django.server | "GET /tests/questions_test/2/ HTTP/1.1" 200 2798
2025-04-24 12:19:54 | INFO | django.server | "POST /tests/questions_test/2/ HTTP/1.1" 302 0
2025-04-24 12:19:54 | INFO | django.server | "GET /tests/test_result/2/ HTTP/1.1" 200 1531
2025-04-24 12:19:57 | INFO | django.server | "GET /users/my_recommendations/ HTTP/1.1" 200 1966
2025-04-24 12:24:12 | INFO | django.server | "GET / HTTP/1.1" 200 4071
2025-04-24 12:27:21 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 12:27:21 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 19:35:12 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:37:12 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:37:15 | ERROR | django.request | Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\middleware.py", line 172, in _postprocess
    rendered = toolbar.render_toolbar()
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\toolbar.py", line 96, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
2025-04-24 19:37:15 | ERROR | django.server | "GET / HTTP/1.1" 500 137056
2025-04-24 19:37:15 | ERROR | django.request | Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\middleware.py", line 172, in _postprocess
    rendered = toolbar.render_toolbar()
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\toolbar.py", line 96, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
2025-04-24 19:37:15 | ERROR | django.server | "GET /favicon.ico HTTP/1.1" 500 136891
2025-04-24 19:39:40 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:39:41 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:39:42 | INFO | django.server | "GET / HTTP/1.1" 200 3562
2025-04-24 19:39:42 | INFO | django.server | "GET /media/tests/image6_vVIDswq.png HTTP/1.1" 304 0
2025-04-24 19:39:42 | INFO | django.server | "GET /media/tests/image5_SBf1jTL.png HTTP/1.1" 304 0
2025-04-24 19:39:42 | INFO | django.server | "GET /media/tests/image5_ifcC45h.png HTTP/1.1" 304 0
2025-04-24 19:39:42 | WARNING | django.request | Not Found: /favicon.ico
2025-04-24 19:39:42 | WARNING | django.server | "GET /favicon.ico HTTP/1.1" 404 2987
2025-04-24 19:40:02 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 19:40:07 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 19:40:07 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:41:38 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:41:39 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:41:41 | ERROR | django.request | Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\middleware.py", line 172, in _postprocess
    rendered = toolbar.render_toolbar()
  File "C:\Users\Admin\Django\env\Lib\site-packages\debug_toolbar\toolbar.py", line 96, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Admin\Django\env\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
2025-04-24 19:41:41 | ERROR | django.server | "GET / HTTP/1.1" 500 137497
2025-04-24 19:42:01 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:42:02 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:42:05 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:42:06 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:42:08 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:42:09 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:43:34 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:43:35 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:43:37 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:17 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:44:18 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:44:24 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:44:25 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:44:26 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:44:27 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:44:30 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:32 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:32 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:32 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:32 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:32 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:32 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:33 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:33 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:33 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:33 | INFO | django.server | "GET / HTTP/1.1" 200 4574
2025-04-24 19:44:36 | INFO | django.server | "GET /users/logout/ HTTP/1.1" 302 0
2025-04-24 19:44:36 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 1430
2025-04-24 19:44:57 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:44:58 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:45:16 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:47:55 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:47:57 | INFO | django.server | "GET / HTTP/1.1" 200 3562
2025-04-24 19:48:28 | INFO | django.utils.autoreload | C:\Users\Admin\Django\testapp\testapp\testapp\settings.py changed, reloading.
2025-04-24 19:48:29 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-24 19:48:43 | INFO | django.server | "GET / HTTP/1.1" 200 17696
2025-04-24 19:48:43 | INFO | django.server | "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 21683
2025-04-24 19:48:43 | INFO | django.server | "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
2025-04-24 19:48:43 | INFO | django.server | "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 14819
2025-04-24 19:48:43 | INFO | django.server | "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4692
2025-04-24 19:48:52 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=VersionsPanel HTTP/1.1" 200 783
2025-04-24 19:48:55 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=HistoryPanel HTTP/1.1" 200 2627
2025-04-24 19:48:55 | INFO | django.server | "GET /static/debug_toolbar/js/history.js HTTP/1.1" 200 3369
2025-04-24 19:48:58 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=SettingsPanel HTTP/1.1" 200 26397
2025-04-24 19:48:59 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=HeadersPanel HTTP/1.1" 200 4850
2025-04-24 19:49:04 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=RequestPanel HTTP/1.1" 200 1381
2025-04-24 19:49:04 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=SQLPanel HTTP/1.1" 200 26906
2025-04-24 19:49:07 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=StaticFilesPanel HTTP/1.1" 200 36700
2025-04-24 19:49:08 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=TemplatesPanel HTTP/1.1" 200 4553
2025-04-24 19:49:09 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=CachePanel HTTP/1.1" 200 1737
2025-04-24 19:49:10 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=SignalsPanel HTTP/1.1" 200 2434
2025-04-24 19:49:14 | INFO | django.server | "GET /users/__debug__/history_refresh/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&exclude_history=True HTTP/1.1" 200 1689
2025-04-24 19:50:18 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&panel_id=AlertsPanel HTTP/1.1" 200 167
2025-04-24 19:50:25 | INFO | django.server | "GET /users/__debug__/history_refresh/?store_id=8365d03da2e04c999ec7d2146c3fc3cc&exclude_history=True HTTP/1.1" 200 1689
2025-04-24 19:50:32 | INFO | django.server | "GET /users/login/ HTTP/1.1" 200 15581
2025-04-24 19:50:32 | INFO | django.server | "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
2025-04-24 19:50:32 | INFO | django.server | "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
2025-04-24 19:50:32 | INFO | django.server | "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
2025-04-24 19:50:32 | INFO | django.server | "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
2025-04-24 19:50:36 | INFO | django.server | "POST /users/login/ HTTP/1.1" 200 15580
2025-04-24 19:50:39 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=c27d39cafce24467936370b1ee137ca9&panel_id=HistoryPanel HTTP/1.1" 200 6437
2025-04-24 19:50:39 | INFO | django.server | "GET /static/debug_toolbar/js/history.js HTTP/1.1" 304 0
2025-04-24 19:50:49 | INFO | django.server | "POST /users/login/ HTTP/1.1" 302 0
2025-04-24 19:50:49 | INFO | django.server | "GET / HTTP/1.1" 200 18708
2025-04-24 19:50:49 | INFO | django.server | "GET /users/__debug__/render_panel/?store_id=bbdebbc2d27a4fc882e4f786b8a6617c&panel_id=HistoryPanel HTTP/1.1" 200 10233
